// <auto-generated />
using System;
using GreenAgriHub.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenAgriHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514194342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("GreenAgriHub.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeePassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeEmail = "jack@gmail.com",
                            EmployeeName = "Jack",
                            EmployeePassword = "jack10"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeEmail = "bob@gmail.com",
                            EmployeeName = "Bob",
                            EmployeePassword = "bob20"
                        });
                });

            modelBuilder.Entity("GreenAgriHub.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FarmerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerSurname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            FarmerId = 1,
                            FarmerEmail = "tnkosi@gmail.com",
                            FarmerName = "Thabo",
                            FarmerPassword = "nkosi123",
                            FarmerPhone = "0612345678",
                            FarmerSurname = "Nkosi"
                        },
                        new
                        {
                            FarmerId = 2,
                            FarmerEmail = "nzondo@gmail.com",
                            FarmerName = "Nathi",
                            FarmerPassword = "zondo123",
                            FarmerPhone = "0712345678",
                            FarmerSurname = "Zondo"
                        });
                });

            modelBuilder.Entity("GreenAgriHub.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GreenAgriHub.Models.Product", b =>
                {
                    b.HasOne("GreenAgriHub.Models.Farmer", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("GreenAgriHub.Models.Farmer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
